export const HOME_SKELETON = {
  EXPERIENCE_CARD_COUNT: 3,
  VOLUNTEERING_CARD_COUNT: 2,
  EDUCATION_CARD_COUNT: 2,
  TESTIMONIAL_CARD_COUNT: 3,
  PROJECT_CARD_COUNT: 4
} as const

export const CV_SKELETON = {
  EXPERIENCE_ENTRY_COUNT: 3
} as const
