export const TESTIMONIAL_CONSTANTS = {
  AUTOPLAY_INTERVAL: 10000,
  HOVER_SCROLL_INTERVAL: 300,
  MIN_SWIPE_DISTANCE: 50,
  LEFT_HOVER_THRESHOLD: 0.2,
  MAX_TEXT_HEIGHT: 120,
  MOBILE_BREAKPOINT: 768,
  TABLET_BREAKPOINT: 1024,
  CARDS_PER_VIEW: {
    MOBILE: 1,
    TABLET: 2,
    DESKTOP: 2
  },
  CAROUSEL_TRANSITION_DURATION_MS: 450,
  CAROUSEL_TRANSITION_EASING: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)'
} as const
