export const CLOSE_ON_DRAG_RATIO = 0.6
export const SNAP_BACK_RATIO = 0.4
export const SNAP_BACK_DURATION_MS = 300
export const MAX_HEIGHT_VH = 80

export const BOTTOM_SHEET_RULES = {
  CLOSE_ON_DRAG_RATIO,
  SNAP_BACK_RATIO,
  SNAP_BACK_DURATION_MS,
  MAX_HEIGHT_VH
} as const

export const BOTTOM_SHEET = BOTTOM_SHEET_RULES