export const DROPDOWN_BREAKPOINT_PX = 480
export const OVERFLOW_CHECK_DEBOUNCE_MS = 200
export const OVERFLOW_CHECK_INITIAL_DELAY_MS = 500

export const SECTION_NAV_TABS = {
  DROPDOWN_BREAKPOINT_PX,
  OVERFLOW_CHECK_DEBOUNCE_MS,
  OVERFLOW_CHECK_INITIAL_DELAY_MS
} as const
