export const SECTION_NAV = {
  DEFAULT_FIRST_SECTION_ID: 'about',
  VIEWPORT_TOP_OFFSET_PX: 140,
  SCROLL_POLL_MAX_FRAMES: 30,
  SCROLL_SETTLE_MS: 1200,
  INTERSECTION_ROOT_MARGIN: '0px 0px -50% 0px',
  INTERSECTION_THRESHOLD: 0
} as const
